### ISSUE TITLE
Pandoc package fails to make pdf

### ISSUE THREAD

**Issue by a59** [tbfisher/sublimetext-Pandoc#21]
I am trying SublimeText3 on OS X and have installed the Pandoc package.

I don't know if I have to do anything else to set this up and can't find any other instructions but when I select Pandoc I only get four options

PDF
Microsoft Word
HTML5
Markdown (Pandoc)

I tried PDF and got this error.

Error when running:

/usr/local/bin/pandoc -f markdown -o /var/folders/cr/4qc8w69d2v17nvgmt0phxxh80000gp/T/tmp25n8ls.pdf

pandoc: pdflatex not found. pdflatex is needed for pdf output.

I also tried Microsoft Word, but it seem to want to open Word, which I don't have on my Mac. 

Where can I look for instructions on how to fix these problems?

**Comment by maccouch** [comment]
where is this added? I have the exact same problem and can't manage to fix it. Already changed every pdflatex path I found to the current correct one: "/Library/TeX/texbin/pdflatex"  (yosemit/el capitan changes)  but I still can't manage it to run. Always complaining about not finding pdflatex. Any hints?

**Comment by codenoxi** [comment]
I changed in the user Pandoc.sublime-settings the following lines:

`"pandoc-path": "/usr/local/bin/pandoc",`
and
`      "PDF": {
        "scope": {
          "text.html": "html",
          "text.html.markdown": "markdown"
        },
        "pandoc-arguments": [
          "-t", "pdf", "--latex-engine=/Library/TeX/texbin/pdflatex"`

works fine now!
