### ISSUE TITLE
Running Pandoc with your package results in output with [CR] displayed for line endings

### ISSUE THREAD

**Issue by gstalnaker** [tbfisher/sublimetext-Pandoc#24]
Though the [CR] are annoying, the line spacing initially looks fine. Those [CR] are interpreted by SublimeText such that if I, say, run HTMLBeautify (which I want to do), I get a blank line following every [CR] in the reformatted text. If I use HTMLPrint the resulting HTML file displayed in a browser also has blank lines inserted. If, say, I use a modified Pandoc entry in your package to create a plaintext output file, I can copy the pandoc output from your package into a new window and the pasted text has extra lines. I've added some screen shots to show what I mean.

I cannot figure out what's going on. I chose your package for its ease of configuring. Pandown, using the same pandoc.exe binary, does not put the [CR] line endings, so it's something your package is doing.

Changing line endings using the Sublime-text menu from Windows to Unix and back changes nothing. If I save/name the output document, close it, then reopen it, the [CR] are gone. So it appears to be something in the buffered output that's removed when the file is saved by ST3. Very odd.

![pandoc plain output 2015-03-02 14_25_22_sublime text](https://cloud.githubusercontent.com/assets/11047967/6450406/41413018-c0ed-11e4-90d7-b944bdc1114a.png)
![pandoc plain output copied to new document in st3 2015-03-02 14_25_22_sublime text](https://cloud.githubusercontent.com/assets/11047967/6450407/41433e30-c0ed-11e4-9948-6f5027b8df6e.png)

**Comment by codeman38** [comment]
Pull request #32 should fix this.

**Comment by gstalnaker** [comment]
Thank you.

On 7/10/2015 9:23 AM, codeman38 wrote:
>
> Pull request #32 
> <https://github.com/tbfisher/sublimetext-Pandoc/pull/32> should fix this.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/tbfisher/sublimetext-Pandoc/issues/24#issuecomment-120421390>.
>

-- 
Guy Stalnaker, PaCS@DOIT, ECM/Imaging Service Lead 115 N. Orchard 
Street, Room 305 RS, Madison WI 53715 guy.stalnaker​@wisc.edu, work 
608.263.8035
