### ISSUE TITLE
Org-mode Support

### ISSUE THREAD

**Issue by Immortalin** [tbfisher/sublimetext-Pandoc#28]
Sublime Text now supports [Org-mode](https://github.com/danielmagnussons/orgmode), what about this?

**Comment by MPvHarmelen** [comment]
This is a feature request for [pandoc](https://pandoc.org/) (which seems to support it), but not this plugin. You can add transformations to your liking in you `User/Pandoc.sublime-settings` and/or create a pull request to add some.

Cheers!
