### ISSUE TITLE
Error when running pandoc

### ISSUE THREAD

**Issue by fusion809** [tbfisher/sublimetext-Pandoc#30]
I have been receiving this error when I run pandoc in Sublime Text 3 (on Windows 7 64 bit, if relevant):

![tmlanguage error pandoc](https://cloud.githubusercontent.com/assets/4717341/7377583/af0119aa-ee2a-11e4-8f2f-6abdf47f982e.png)

I have installed pandoc 1.13.2 via the MSI windows installer. I have also added the MarkdownEditing package.

**Comment by tbfisher** [comment]
Pandoc does not support XML in a generic way. 

If you can transform your document using the `pandoc` command you should be able to configure this plugin to do the same.
