### ISSUE TITLE
Cannot convert HTML to MD [no-wrap is deprecated]

### ISSUE THREAD

**Issue by gmask** [tbfisher/sublimetext-Pandoc#38]
I'm having trouble getting the HTML -> Markdown conversion to work. The error says: 

> -no-wrap is deprecated, use wrap=none instead

![pandoc-nowrap](https://cloud.githubusercontent.com/assets/6797513/14368985/4032c756-fcd6-11e5-8e74-45637b84d13d.gif)

How can I fix this?

**Comment by tbfisher** [comment]
fixed by 1d1e4a3272ffe3589d8afa477dc9ba46d7f0ff0c
