### ISSUE TITLE
Latex Engine specification in default config breaks non-Windows platforms

### ISSUE THREAD

**Issue by darthoctopus** [tbfisher/sublimetext-Pandoc#39]
specifically, in the default configs for beamer and s5, we have as one of the arguments

    "--latex-engine=C:/Program Files (x86)/MiKTeX 2.9/miktex/bin/pdflatex.exe"

which naturally breaks on linux etc. Please don't do this. In most sane configurations the latex engine should already be in $PATH. Alternatively, provide a way to let us specify a latex engine elsewhere that is used for any latex-based output format.

**Comment by tbfisher** [comment]
fixed by 799b597abe1dc5a3000664600bc82cc3ec46b900
