### ISSUE TITLE
remove pandoc.py:109 cmd.extend(['-f', iformat]) line

### ISSUE THREAD

**Issue by cpkio** [tbfisher/sublimetext-Pandoc#53]
**pandoc.py:109** `cmd.extend(['-f', iformat])` should be removed or optioned, since output options should be in .settings file, not in code. Now this `cmd.extend(['-f', iformat])` results in `-f markdown` in my command line, where I want to set the -f params manually.

**Comment by geniusupgrader** [comment]
I think you can already set the -f parameter manually by changing the settings "scope" in the settings file.
So, for example change the "html" to whatever you like: 
```
"scope": {
    "text.html": "html"
},
```
It works for me, when  appending it with [Non-pandoc extensions](http://pandoc.org/MANUAL.html#non-pandoc-extensions). At least the pandoc command from the console output is correct.
