### ISSUE TITLE
Specifying "font_size" and other sublime settings in Pandoc.sublime-settings

### ISSUE THREAD

**Issue by abers** [tbfisher/sublimetext-Pandoc#62]
I realise I am likely making a noob mistake - but is it possible to specify a font_size etc for any document open using the pandoc syntax within Pandoc.sublime-settings?
For example, within Python.sublime-settings I have:
```
{
"font_size": 10,
...
}
```
Which sets the font size for all .py documents to 10 and works the same within other Language.sublime-settings. However, including it or any other sublime setting in Pandoc.sublime-settings seems to have no effect.

**Comment by MPvHarmelen** [comment]
Hi. This plugin doesn't contain syntax definitions. To change syntax-specific settings, open a file with the syntax of which you want to chance the settings and then go to Preferences > Settings - Syntax Specific.
