### ISSUE TITLE
Master release isn't directly installable via PackageControl 

### ISSUE THREAD

**Issue by dahanbn** [tbfisher/sublimetext-Pandoc#64]
You specified two releases that point to the 1.x and 2.x branches respectively. So it isn't possible to install the latest master release via PackageControl.

Your 2.x branch for ST3 doesn't include the latest commits for output-local. Please change that.

**Comment by MPvHarmelen** [comment]
I also noticed that the latest changes in the master branch (including the ones relating to `output-local`) aren't reflected in the package downloadable from packagecontrol.io.

@tbfisher, would it be possible to fix that?

**Comment by MPvHarmelen** [comment]
@tbfisher, would you mind explaining why you closed this issue without fixing and/or commenting about it? I understand you don't want every new commit to be used immediately, but is it possible to update the now four year old 2.x release?

**Comment by tbfisher** [comment]
@MPvHarmelen I created a new release as requested.

**Comment by MPvHarmelen** [comment]
Thanks! Sorry for being impatient :(

**Comment by MPvHarmelen** [comment]
@tbfisher, it's me again... Thanks again for creating the release. It seems, however, that the version on [packagecontrol](https://packagecontrol.io/packages/Pandoc) is still from 2016:

> Versions
> 2016.08.23.12.02.28
> 2016.08.23.12.01.10
> Modified
> 4 years ago

**Comment by tbfisher** [comment]
@MPvHarmelen thanks so much, I"ve sent an email.

I updated the 2.x branch, that should get packagecontrol to get the new version shortly.
