### ISSUE TITLE
Markdown to Docx fails to render links correctly for complicated URLS

### ISSUE THREAD

**Issue by klreeher** [tbfisher/sublimetext-Pandoc#66]
Issue noticed on: Sublime Text 3.0 Build 3143

When I use Pandoc to convert a Markdown file to a DocX, I'm finding that hyperlinks with complicated URLs like, for example, Jira comment permalinks, fail to render correctly.

Markdown example:
```markdown
[link to the comment](https://jira.atlassian.com/browse/TRANS-2476?focusedCommentId=1627205&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1627205)
```

This renders in DocX as:

```
[link to the comment](https://jira.atlassian.com/browse/TRANS-2476?focusedCommentId=1627205&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1627205)
```

Otherwise, the DocX is rendering correctly, and other, less complicated hyperlinks render correctly. No errors are shown in the Sublime Text console. The same markdown file renders correctly with a HTML output.

**Comment by MPvHarmelen** [comment]
Unfortunately, this plugin has no influence on how the content is processed: it only deals with creating the pandoc command to run. If you still have this problem, you could file a bug [upstream](https://github.com/jgm/pandoc).
