### ISSUE TITLE
Pandoc `--atx-headers` flag deprecated

### ISSUE THREAD

**Issue by jacobmovingfwd** [tbfisher/sublimetext-Pandoc#79]
https://pandoc.org/releases.html#pandoc-2.11.2-2020-11-19

> - Default to using ATX (##-style) headings for Markdown output (#6662, Aner Lucero). Previously we used Setext (underlined) headings by default for levels 1–2.
> - Add option `--markdown-headings=atx|setext`, and deprecate `--atx-headers` (#6662, Aner Lucero).
> - Support markdown-headings in defaults files.

**Comment by MPvHarmelen** [comment]
Good catch. If you could make a pull request that fixes the issue, that would be lovely!

**Comment by jacobmovingfwd** [comment]
I found where the change was, then forgot to come back for the PR yesterday, thanks for the reminder!
